public class HebCalConversionObject  {

        public Integer gy {get;set;} //Gregorian Year
        public Integer gm {get;set;} //Gregorian Month
        public Integer gd {get;set;} //Gregorian Day



        public Integer hy {get;set;} //Hebrew year
        public Integer hd {get;set;} //Hebrew day of month
        public String  hm {get;set;} //Hebrew month
        public String  hebrew {get;set;}
        public String[] events = new String[]{};

}